name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.15.61
  permission_handler: ^11.3.1
  audio_session: ^0.1.21
  path_provider: ^2.1.4
  intl: ^0.17.0
  record: ^5.1.2
  http: ^1.2.2
  archive: ^3.6.1
  flutter_markdown: ^0.7.4+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
